### ISSUE TITLE
Findings in the docs

### ISSUE THREAD

**Issue by 68040** [clvLabs/PyATEMMax#18]
Some little findings in the docs

# docs/data/protocol
- The "t" is missing in "swicher" in the complete doc. 
- swicher.atem.switcherPortTypes: Typo. The point "multiviewer" is written with a lower "V"
- swicher.atem.mixEffects `mixEffect1..4`: Range. The values are 0..3

# docs/logging/
- `switcher.setLogLevel(logging.DEBUG)`: This loglevel has no effect

# docs/methods/exec/
- execCutME, execAutoME, execFadeToBlackME `mE: see ATEMMixEffects`: There's no "ATEMMixEffects"-reference in the docs.

# docs/methods/set/
- setCameraControlZoomSpeed `zoomSpeed (float): 0.0-1.0`: The range of zoom speed values should be -1.0-1.0

# docs/examples/scan/
- `for i in range(1,255):` The loop should stop at 254 

# docs/examples/scan-query/
- The loop should stop at 254 `for i in range(1,255):`

**Comment by sierrax369** [comment]
switcher.atem.mixeffects `mixEffect1..4`: The names are MixEffect1..4 the values are 0..3
`>>> switcher.atem.mixEffects.mixEffect1   
PyATEMMax.ATEMProtocolEnums.ATEMConstant(name=mixEffect1, value=0)`

**Comment by clvLabs** [comment]
Let's see if I can answer them all...


## docs/data/protocol
- >The "t" is missing in "swicher" in the complete doc.
  - [Pull request #24](https://github.com/clvLabs/PyATEMMax/pull/24) merged, thanks !!
  - Also found an extra one and [fixed it](https://github.com/clvLabs/PyATEMMax/commit/1776d60) (sorry, forgot to link the commit to this issue).
- >swicher.atem.switcherPortTypes: Typo. The point "multiviewer" is written with a lower "V"
  - Fixed with [this commit](https://github.com/clvLabs/PyATEMMax/commit/5c0a733).
- >swicher.atem.mixEffects `mixEffect1..4`: Range. The values are 0..3
  - As pointed by @sierrax369, the value of `mixEffects.mixEffect1` is `0` and so on...
  - Anyway, I [added an extra comment in the docs](https://github.com/clvLabs/PyATEMMax/commit/68e123e), just in case.

## docs/logging/
- >`switcher.setLogLevel(logging.DEBUG)`: This loglevel has no effect
  - Doesn't it ? I just tried it with the [scheduled-tasks example](https://github.com/clvLabs/PyATEMMax/blob/master/examples/scheduled-tasks.py), and if I change the log level in [line 103](https://github.com/clvLabs/PyATEMMax/blob/1776d60/examples/scheduled-tasks.py#L103) to `logging.DEBUG` the output of the example changes substantially. Please tell me if it doesn't work for you (or open a separate issue).

## docs/methods/exec/
- >execCutME, execAutoME, execFadeToBlackME `mE: see ATEMMixEffects`: There's no "ATEMMixEffects"-reference in the docs.
  - Yes, you are right :) The reference talks about [this class in the code](https://github.com/clvLabs/PyATEMMax/blob/6dbff189e9e7e3fb235d2ee54ed641c800885c8a/PyATEMMax/ATEMProtocolEnums.py#L448).
  - If you try to find "mixEffects" in [the protocol constants page](https://clvlabs.github.io/PyATEMMax/docs/data/protocol/) of the docs you'll be able to find it.
  - Anyway, I [added the class names](https://github.com/clvLabs/PyATEMMax/commit/41801ff) in this list.

## docs/methods/set/
- >setCameraControlZoomSpeed `zoomSpeed (float): 0.0-1.0`: The range of zoom speed values should be -1.0-1.0
  - It turns out not only the docs were wrong, the code also was using that range.
  - Fixed with [this commit](https://github.com/clvLabs/PyATEMMax/commit/b3cc10c).

## docs/examples/scan/
- >`for i in range(1,255):` The loop should stop at 254
  - As pointed by @sierrax369, `range(1,255)` returns values from `0` to `254` (see [Python range docs](https://docs.python.org/3/library/stdtypes.html#typesseq-range)).

## docs/examples/scan-query/
- > The loop should stop at 254 `for i in range(1,255):`
  - Same as before.

**Comment by clvLabs** [comment]
Version 1.0b8 already available.

**Comment by sierrax369** [comment]
"As pointed by @sierrax369, range(1,255) returns values from 0 to 254 (see [Python range docs](https://docs.python.org/3/library/stdtypes.html#typesseq-range))."
values from 1 to 254 ;-)
